I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sim.rpy", line 12, in script call
    call screen tie
  File "game/sim2.rpy", line 9, in script call
    call screen sit
  File "game/control.rpy", line 603, in script
    p "Aaaargh!" with hpucnh
  File "game/control.rpy", line 603, in <module>
    p "Aaaargh!" with hpucnh
NameError: name 'hpucnh' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sim.rpy", line 12, in script call
    call screen tie
  File "game/sim2.rpy", line 9, in script call
    call screen sit
  File "game/control.rpy", line 603, in script
    p "Aaaargh!" with hpucnh
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 707, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\ast.py", line 537, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\PROGRAM\RENPYY\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/control.rpy", line 603, in <module>
    p "Aaaargh!" with hpucnh
NameError: name 'hpucnh' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Pride and Submission 1.3.4-Beta
Wed Aug 11 23:25:15 2021
