I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/event.rpy", line 39, in script
    show m_tired at s
  File "game/event.rpy", line 260, in <module>
    if clean<=30 and clean>0:
NameError: name 'mosFirst' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/event.rpy", line 39, in script
    show m_tired at s
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\ast.py", line 1807, in execute
    if renpy.python.py_eval(condition):
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\python.py", line 1961, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\python.py", line 1954, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/event.rpy", line 260, in <module>
    if clean<=30 and clean>0:
NameError: name 'mosFirst' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Pride and Submission 1.1
Sun Dec 01 02:35:27 2019
