I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/bath.rpy", line 2880, in script
    "[d] graphs [p]'s head and pushes [p] mouth to his chest."
Exception: Parameter 'new_widget' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/sim.rpy", line 11, in script call
    call screen tie
  File "game/bath.rpy", line 2880, in script
    "[d] graphs [p]'s head and pushes [p] mouth to his chest."
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\ast.py", line 1375, in execute
    renpy.exports.with_statement(trans, paired)
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\exports.py", line 1578, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\display\core.py", line 2240, in do_with
    clear=clear)
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\display\core.py", line 2690, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\display\core.py", line 3027, in interact_core
    new_widget=layers_root)
  File "D:\PROGRAM\RENPY\renpy-6.99.14-sdk\renpy\atl.py", line 436, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'new_widget' is not known by ATL Transform.

Windows-8-6.2.9200
Ren'Py 7.2.2.491
Pride and Submission 1.1
Sat Nov 30 23:21:40 2019
